In [1]:
# 数组
from array import array
from random import random
floats = array('d', (random() for i in range(10**7)))

floats[-1]

0.8486537983821256

In [2]:
fp = open('floats.bin', 'wb')
floats.tofile(fp)
fp.close()

In [3]:
floats2 = array('d')
fp = open('floats.bin', 'rb')
floats2.fromfile(fp, 10**7)
fp.close()
floats2[-1]

0.8486537983821256

In [4]:
# numpy
import numpy
a = numpy.arange(12)

a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
type(a)

numpy.ndarray

In [6]:
a.shape

(12,)

In [7]:
a.shape = 3, 4

In [8]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [9]:
a[2]

array([ 8,  9, 10, 11])

In [10]:
a[2, 1]

9

In [11]:
a[:, 1]

array([1, 5, 9])

In [12]:
a.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [30]:
# 双向队列和其他形式的队列
from collections import deque
dq = deque(range(10), maxlen=10)

dq

deque([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
dq.rotate(3)

dq

deque([7, 8, 9, 0, 1, 2, 3, 4, 5, 6])

In [32]:
dq.appendleft(-1)

dq

deque([-1, 7, 8, 9, 0, 1, 2, 3, 4, 5])

In [33]:
dq.extend([11, 22, 33])

# maxlen=10
dq

deque([9, 0, 1, 2, 3, 4, 5, 11, 22, 33])

In [34]:
dq.extendleft([10, 20, 30, 40])

dq

deque([40, 30, 20, 10, 9, 0, 1, 2, 3, 4])